"use strict";

// Content definitions are separate from UI code so future systems can query them by stable ID.
const ITEM_DEFINITIONS = Object.freeze({
  arthur_sword: {
    id: "arthur_sword",
    name: "Iron Longsword",
    description: "A dependable blade from before the days of legend.",
    category: "weapon",
    tags: ["martial", "steel"],
    equippable: true,
    equipmentSlot: "weapon",
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
  },
  quilted_hauberk: {
    id: "quilted_hauberk",
    name: "Chainmail Hauberk",
    description: "A dependable mail shirt suited to road and battlefield.",
    category: "armor",
    tags: ["armor", "light"],
    equippable: true,
    equipmentSlot: "armor",
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
  },
  wayfarers_cloak: {
    id: "wayfarers_cloak",
    name: "Traveler's Cloak",
    description: "A thick green cloak that sheds rain and conceals its wearer.",
    category: "gear",
    tags: ["travel", "forest"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
  },
  rope: {
    id: "rope",
    name: "Rope",
    description: "A sturdy coil useful for obstacles and difficult ground.",
    category: "gear",
    tags: ["travel", "tool", "mundane"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
  },
  silver_stag_medallion: {
    id: "silver_stag_medallion",
    name: "Silver Stag Medallion",
    description: "An old silver medallion depicting a stag. Its purpose is unknown.",
    category: "relic",
    tags: ["silver", "stag", "unknown"],
    equippable: true,
    equipmentSlot: "relic",
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
    sellable: false,
    protected: true,
  },
  torch: {
    id: "torch",
    name: "Torch",
    description: "A pitch-soaked torch for lighting a dark road.",
    category: "supply",
    tags: ["mundane", "light", "consumable"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: true,
    maxStack: 4,
    effects: {},
    questItem: false,
  },
  old_coin: {
    id: "old_coin",
    name: "Old Silver Coins",
    description: "Old silver coins bearing the face of a forgotten ruler.",
    category: "valuable",
    rarity: "common",
    tags: ["mundane", "coin", "valuable"],
    equippable: false,
    equipmentSlot: null,
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
  },
  hunting_supplies: {
    id: "hunting_supplies",
    name: "Hunting Supplies",
    description: "Twine, hooks, and other practical tools for living off the road.",
    category: "gear",
    tags: ["mundane", "hunting", "supplies"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
  },
  bandages: {
    id: "bandages",
    name: "Bandages",
    description: "Clean strips of linen suitable for dressing wounds.",
    category: "consumable",
    rarity: "common",
    tags: ["mundane", "medical", "consumable"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: true,
    maxStack: 4,
    effects: {},
    questItem: false,
  },
  dried_herbs: {
    id: "dried_herbs",
    name: "Dried Herbs",
    description: "A bundle of useful woodland herbs.",
    category: "consumable",
    rarity: "common",
    tags: ["mundane", "woodland", "consumable"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: true,
    maxStack: 4,
    effects: {},
    questItem: false,
  },
  fine_hunting_knife: {
    id: "fine_hunting_knife",
    name: "Fine Hunting Knife",
    description: "A well-made hunting knife with a keen edge.",
    category: "gear",
    rarity: "uncommon",
    tags: ["mundane", "tool", "hunting"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
  },
  hunters_charm: {
    id: "hunters_charm",
    name: "Hunter's Charm",
    description: "A small antler charm worn smooth by years of handling.",
    category: "relic",
    rarity: "uncommon",
    tags: ["trinket", "antler", "unknown"],
    equippable: true,
    equipmentSlot: "relic",
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
  },
  antler_fragment: {
    id: "antler_fragment",
    name: "Antler Fragment",
    description: "A polished fragment of antler marked with shallow cuts.",
    category: "curiosity",
    rarity: "uncommon",
    tags: ["antler", "unknown"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
  },
  strange_seeds: {
    id: "strange_seeds",
    name: "Strange Seeds",
    description: "Dark seeds from a plant Arthur does not recognize.",
    category: "curiosity",
    rarity: "uncommon",
    tags: ["plant", "unknown"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
  },
  green_glass_vial: {
    id: "green_glass_vial",
    name: "Green Glass Vial",
    description: "A tiny green glass vial sealed with black wax.",
    category: "curiosity",
    rarity: "rare",
    tags: ["vial", "sealed", "unknown"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
  },
});

const KNOWLEDGE_DEFINITIONS = Object.freeze({
  woodcraft: {
    id: "woodcraft",
    name: "Woodcraft",
    description: "Basic knowledge of trails, hunting, and wilderness travel.",
    tags: ["mundane", "wilderness", "travel"],
  },
});

const COMPANION_DEFINITIONS = Object.freeze({
  sir_kay: {
    id: "sir_kay",
    name: "Sir Kay",
    description: "A blunt, steadfast knight who knows the cost of an expedition.",
    tags: ["knight", "practical"],
  },
});

const CHAPTER_DEFINITIONS = Object.freeze([
  { id: "chapter_01", number: "I", name: "Completed", regionId: null },
  { id: "chapter_02", number: "II", name: "Completed", regionId: null },
  { id: "chapter_03", number: "III", name: "Brocéliande", regionId: "broceliande" },
  { id: "chapter_04", number: "IV", name: "???", regionId: null },
  { id: "chapter_05", number: "V", name: "???", regionId: null },
]);
