"use strict";

// Content definitions are separate from UI code so future systems can query them by stable ID.
const ITEM_DEFINITIONS = Object.freeze({
  arthur_sword: {
    id: "arthur_sword",
    name: "Arthur's Sword",
    description: "A dependable blade from before the days of legend.",
    category: "weapon",
    tags: ["martial", "steel"],
    equippable: true,
    slot: "weapon",
    effects: {},
    questItem: false,
  },
  quilted_hauberk: {
    id: "quilted_hauberk",
    name: "Quilted Hauberk",
    description: "Travel-worn protection suited to a long forest road.",
    category: "armor",
    tags: ["armor", "light"],
    equippable: true,
    slot: "armor",
    effects: {},
    questItem: false,
  },
  wayfarers_cloak: {
    id: "wayfarers_cloak",
    name: "Wayfarer's Cloak",
    description: "A thick green cloak that sheds rain and conceals its wearer.",
    category: "gear",
    tags: ["travel", "forest"],
    equippable: true,
    slot: "utility",
    effects: {},
    questItem: false,
  },
  rope: {
    id: "rope",
    name: "Rope",
    description: "A sturdy coil useful for obstacles and difficult ground.",
    category: "gear",
    tags: ["travel", "tool", "mundane"],
    equippable: true,
    slot: "utility",
    effects: {},
    questItem: false,
  },
  silver_stag_medallion: {
    id: "silver_stag_medallion",
    name: "Silver Stag Medallion",
    description: "An old silver medallion depicting a stag. Its purpose is unknown.",
    category: "relic",
    tags: ["silver", "stag", "unknown"],
    equippable: true,
    slot: "utility",
    effects: {},
    questItem: false,
  },
  torch: {
    id: "torch",
    name: "Torch",
    description: "A pitch-soaked torch for lighting a dark road.",
    category: "supply",
    tags: ["mundane", "light", "consumable"],
    equippable: false,
    slot: null,
    effects: {},
    questItem: false,
  },
  old_coin: {
    id: "old_coin",
    name: "Old Coin",
    description: "A worn coin left behind at a forest camp.",
    category: "treasure",
    tags: ["mundane", "coin"],
    equippable: false,
    slot: null,
    effects: {},
    questItem: false,
  },
  hunting_supplies: {
    id: "hunting_supplies",
    name: "Hunting Supplies",
    description: "Twine, hooks, and other practical tools for living off the road.",
    category: "gear",
    tags: ["mundane", "hunting", "supplies"],
    equippable: false,
    slot: null,
    effects: {},
    questItem: false,
  },
  bandages: {
    id: "bandages",
    name: "Bandages",
    description: "Clean linen strips suitable for treating minor injuries.",
    category: "supply",
    tags: ["mundane", "medical"],
    equippable: false,
    slot: null,
    effects: {},
    questItem: false,
  },
});

const KNOWLEDGE_DEFINITIONS = Object.freeze({
  woodcraft: {
    id: "woodcraft",
    name: "Woodcraft",
    description: "Basic knowledge of trails, hunting, and wilderness travel.",
    tags: ["mundane", "wilderness", "travel"],
  },
});

const COMPANION_DEFINITIONS = Object.freeze({
  sir_kay: {
    id: "sir_kay",
    name: "Sir Kay",
    description: "A blunt, steadfast knight who knows the cost of an expedition.",
    tags: ["knight", "practical"],
  },
});

const CHAPTER_DEFINITIONS = Object.freeze([
  { id: "chapter_01", number: "I", name: "Completed", regionId: null },
  { id: "chapter_02", number: "II", name: "Completed", regionId: null },
  { id: "chapter_03", number: "III", name: "Brocéliande", regionId: "broceliande" },
  { id: "chapter_04", number: "IV", name: "???", regionId: null },
  { id: "chapter_05", number: "V", name: "???", regionId: null },
]);
