"use strict";

// Content definitions are separate from UI code so future systems can query them by stable ID.
const ITEM_DEFINITIONS = Object.freeze({
  arthur_sword: {
    id: "arthur_sword",
    name: "Iron Longsword",
    description: "A dependable blade from before the days of legend.",
    category: "weapon",
    tags: ["martial", "steel"],
    equippable: true,
    equipmentSlot: "weapon",
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
    unique: true,
  },
  quilted_hauberk: {
    id: "quilted_hauberk",
    name: "Chainmail Hauberk",
    description: "A dependable mail shirt suited to road and battlefield.",
    category: "armor",
    tags: ["armor", "light"],
    equippable: true,
    equipmentSlot: "armor",
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
    unique: true,
  },
  wayfarers_cloak: {
    id: "wayfarers_cloak",
    name: "Traveler's Cloak",
    description: "A thick green cloak that sheds rain and conceals its wearer.",
    category: "gear",
    tags: ["travel", "forest"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
  },
  rope: {
    id: "rope",
    name: "Rope",
    description: "A sturdy coil useful for obstacles and difficult ground.",
    category: "gear",
    tags: ["travel", "tool", "mundane"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
  },
  silver_stag_medallion: {
    id: "silver_stag_medallion",
    name: "Silver Stag Medallion",
    description: "An old silver medallion depicting a stag. Its purpose is unknown.",
    category: "relic",
    tags: ["silver", "stag", "unknown"],
    equippable: true,
    equipmentSlot: "relic",
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
    sellable: false,
    protected: true,
  },
  torch: {
    id: "torch",
    name: "Torch",
    description: "A pitch-soaked torch for lighting a dark road.",
    category: "supply",
    tags: ["mundane", "light", "consumable"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: true,
    maxStack: 4,
    effects: {},
    questItem: false,
  },
  old_coin: {
    id: "old_coin",
    name: "Old Silver Coins",
    description: "Old silver coins bearing the face of a forgotten ruler.",
    category: "valuable",
    rarity: "common",
    tags: ["mundane", "coin", "valuable"],
    equippable: false,
    equipmentSlot: null,
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
  },
  silver_brooch: {
    id: "silver_brooch",
    name: "Silver Brooch",
    description: "A small silver brooch decorated with worn knotwork.",
    category: "valuable",
    rarity: "common",
    tags: ["mundane", "silver", "valuable"],
    equippable: false,
    equipmentSlot: null,
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
  },
  amber_beads: {
    id: "amber_beads",
    name: "Amber Beads",
    description: "A short string of polished amber beads.",
    category: "valuable",
    rarity: "common",
    tags: ["mundane", "valuable"],
    equippable: false,
    equipmentSlot: null,
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
  },
  decorated_buckle: {
    id: "decorated_buckle",
    name: "Decorated Buckle",
    description: "A bronze belt buckle worked with an intricate pattern.",
    category: "valuable",
    rarity: "common",
    tags: ["mundane", "bronze", "valuable"],
    equippable: false,
    equipmentSlot: null,
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
  },
  merchants_ring: {
    id: "merchants_ring",
    name: "Merchant's Ring",
    description: "A heavy silver ring marked with a merchant's seal.",
    category: "valuable",
    rarity: "uncommon",
    tags: ["silver", "valuable"],
    equippable: false,
    equipmentSlot: null,
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
  },
  carved_ivory_token: {
    id: "carved_ivory_token",
    name: "Carved Ivory Token",
    description: "A small carved token yellowed with age.",
    category: "valuable",
    rarity: "uncommon",
    tags: ["curiosity", "valuable"],
    equippable: false,
    equipmentSlot: null,
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
  },
  bronze_figurine: {
    id: "bronze_figurine",
    name: "Bronze Figurine",
    description: "A palm-sized bronze figure worn smooth by handling.",
    category: "valuable",
    rarity: "uncommon",
    tags: ["bronze", "curiosity", "valuable"],
    equippable: false,
    equipmentSlot: null,
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
  },
  polished_agate: {
    id: "polished_agate",
    name: "Polished Agate",
    description: "A smooth banded stone polished to a glossy finish.",
    category: "valuable",
    rarity: "uncommon",
    tags: ["stone", "valuable"],
    equippable: false,
    equipmentSlot: null,
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
  },
  embroidered_gloves: {
    id: "embroidered_gloves",
    name: "Embroidered Gloves",
    description: "A pair of finely embroidered gloves, slightly weather-stained.",
    category: "valuable",
    rarity: "uncommon",
    tags: ["cloth", "valuable"],
    equippable: false,
    equipmentSlot: null,
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
  },
  silver_cup: {
    id: "silver_cup",
    name: "Silver Cup",
    description: "A small silver drinking cup, dented but still valuable.",
    category: "valuable",
    rarity: "rare",
    tags: ["silver", "valuable"],
    equippable: false,
    equipmentSlot: null,
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
  },
  coin_purse: {
    id: "coin_purse",
    name: "Coin Purse",
    description: "A small leather purse containing mixed old coins.",
    category: "valuable",
    rarity: "common",
    tags: ["mundane", "coin", "valuable"],
    equippable: false,
    equipmentSlot: null,
    carriable: false,
    consumable: false,
    effects: {},
    questItem: false,
  },
  hunting_supplies: {
    id: "hunting_supplies",
    name: "Hunting Supplies",
    description: "Twine, hooks, and other practical tools for living off the road.",
    category: "gear",
    tags: ["mundane", "hunting", "supplies"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
  },
  bandages: {
    id: "bandages",
    name: "Bandages",
    description: "Clean strips of linen suitable for dressing wounds.",
    category: "consumable",
    rarity: "common",
    tags: ["mundane", "medical", "consumable"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: true,
    maxStack: 4,
    effects: {},
    questItem: false,
  },
  dried_herbs: {
    id: "dried_herbs",
    name: "Dried Herbs",
    description: "A bundle of useful woodland herbs.",
    category: "consumable",
    rarity: "common",
    tags: ["mundane", "woodland", "consumable"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: true,
    maxStack: 4,
    effects: {},
    questItem: false,
  },
  fine_hunting_knife: {
    id: "fine_hunting_knife",
    name: "Fine Hunting Knife",
    description: "A well-made hunting knife with a keen edge.",
    category: "gear",
    rarity: "uncommon",
    tags: ["mundane", "tool", "hunting"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
    unique: true,
  },
  hunters_charm: {
    id: "hunters_charm",
    name: "Hunter's Charm",
    description: "A small antler charm worn smooth by years of handling.",
    category: "relic",
    rarity: "uncommon",
    tags: ["trinket", "antler", "unknown"],
    equippable: true,
    equipmentSlot: "relic",
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
  },
  antler_fragment: {
    id: "antler_fragment",
    name: "Antler Fragment",
    description: "A polished fragment of antler marked with shallow cuts.",
    category: "curiosity",
    rarity: "uncommon",
    tags: ["antler", "unknown"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
  },
  strange_seeds: {
    id: "strange_seeds",
    name: "Strange Seeds",
    description: "Dark seeds from a plant Arthur does not recognize.",
    category: "curiosity",
    rarity: "uncommon",
    tags: ["plant", "unknown"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
  },
  green_glass_vial: {
    id: "green_glass_vial",
    name: "Green Glass Vial",
    description: "A tiny green glass vial sealed with black wax.",
    category: "curiosity",
    rarity: "rare",
    tags: ["vial", "sealed", "unknown"],
    equippable: false,
    equipmentSlot: null,
    carriable: true,
    consumable: false,
    effects: {},
    questItem: false,
  },
});

const KNOWLEDGE_DEFINITIONS = Object.freeze({
  woodcraft: {
    id: "woodcraft",
    name: "Woodcraft",
    description: "Basic knowledge of trails, hunting, and wilderness travel.",
    tags: ["mundane", "wilderness", "travel"],
  },
});

const PLAYER_CHARACTER_DEFINITION = Object.freeze({
  id: "arthur",
  name: "Arthur",
  provisionCapacity: 20,
  provisionConsumptionMultiplier: 1,
});

const COMPANION_DEFINITIONS = Object.freeze({
  sir_kay: {
    id: "sir_kay",
    name: "Sir Kay",
    description: "A blunt, steadfast knight who knows the cost of an expedition.",
    tags: ["knight", "practical"],
    provisionCapacityBonus: 10,
    provisionConsumptionBonus: 0.3,
  },
});

const CHAPTER_DEFINITIONS = Object.freeze([
  { id: "chapter_01", number: "I", name: "Completed", regionId: null },
  { id: "chapter_02", number: "II", name: "Completed", regionId: null },
  { id: "chapter_03", number: "III", name: "Brocéliande", regionId: "broceliande" },
  { id: "chapter_04", number: "IV", name: "???", regionId: null },
  { id: "chapter_05", number: "V", name: "???", regionId: null },
]);
