"""Persistent health, Inn healing, and campaign-simulation browser regressions."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
import threading
import time
from http.server import ThreadingHTTPServer
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))

from location_system_test import CHROME, DevTools, QuietHandler, ROOT, free_port, wait_for_json


def run():
    os.chdir(ROOT)
    http_port = free_port()
    debug_port = free_port()
    server = ThreadingHTTPServer(("127.0.0.1", http_port), QuietHandler)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    profile = Path(tempfile.mkdtemp(prefix="grail-campaign-test-"))
    game_url = f"http://127.0.0.1:{http_port}/"
    chrome = subprocess.Popen([
        str(CHROME), "--headless=new", "--disable-gpu", "--no-sandbox",
        "--remote-allow-origins=*", f"--remote-debugging-port={debug_port}",
        f"--user-data-dir={profile}", game_url,
    ], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    checks = 0
    try:
        devtools = DevTools(wait_for_json(debug_port, game_url))
        devtools.call("Runtime.enable")
        time.sleep(0.3)
        devtools.evaluate("localStorage.clear(); location.reload()")
        time.sleep(0.3)

        def check(expression: str, label: str):
            nonlocal checks
            if not devtools.evaluate(expression):
                raise AssertionError(label)
            checks += 1

        check("PLAYER_CHARACTER_DEFINITION.combat.maxHp===40 && game.player.arthurHealth===40", "Arthur's authoritative/reset health is not 40")
        check("COMPANION_DEFINITIONS.sir_kay.combat.maxHp===50 && game.player.saveVersion===6 && game.player.companionStates.sir_kay.health===50", "Kay's data-defined/reset health is not 50")
        check("sanitizePlayerState({saveVersion:5},SaveSystem.createDefaultPlayerState()).arthurHealth===40", "Old save did not migrate to valid persistent health")
        check("sanitizePlayerState({saveVersion:6,companionStates:{sir_kay:{health:85}}},SaveSystem.createDefaultPlayerState()).companionStates.sir_kay.health===50", "Old Kay health above the new maximum was not clamped")
        check("(() => { const ids=['silver_reliquary','gilded_brooch','roman_signet','jeweled_saints_locket']; const player=SaveSystem.createDefaultPlayerState(); const failed=ExpeditionRules.startExpedition(player,{provisions:1}); failed.unsecuredLoot=ids.map(itemId=>({itemId,quantity:1})); ExpeditionRules.settle(player,failed,false); if(ids.some(itemId=>player.ownedItems[itemId])) return false; const returned=ExpeditionRules.startExpedition(player,{provisions:1}); returned.unsecuredLoot=ids.map(itemId=>({itemId,quantity:1})); ExpeditionRules.settle(player,returned,true); const goldBefore=player.currentGold; const sales=CampaignRules.sellMerchantItems(player,returned.unsecuredLoot); return sales.goldEarned===90&&player.currentGold-goldBefore===90&&JSON.stringify(sales.sales.map(sale=>sale.goldEarned))==='[15,20,25,30]'&&ids.every(itemId=>!player.ownedItems[itemId]); })()", "Rare treasures did not remain unsecured on failure or auto-sell at authored values")

        devtools.click('[data-action="enter-location"]')
        devtools.click('[data-destination-id="inn"]')
        devtools.evaluate("game.player.arthurHealth=20; game.player.companionStates.sir_kay.health=30; game.player.selectedCompanion='sir_kay'; game.player.currentGold=12; savePlayer(); renderDestination()")
        check("document.body.textContent.includes(\"Arthur's Health: 20 / 40\") && document.body.textContent.includes(\"Sir Kay's Health: 30 / 50\") && document.body.textContent.match(/Restore 10 health/g).length===2 && document.body.textContent.includes('whole active party')", "Inn did not show both active-party health quotes")
        devtools.click('[data-action="rest-at-inn"]')
        check("game.player.arthurHealth===30 && game.player.companionStates.sir_kay.health===40 && game.player.currentGold===9 && document.body.textContent.includes('active party rests')", "One flat-cost Inn rest did not heal Arthur and Kay")
        check("SaveSystem.load().arthurHealth===30 && SaveSystem.load().companionStates.sir_kay.health===40 && SaveSystem.load().currentGold===9", "Party healing did not persist through save/load")

        devtools.evaluate("game.player.arthurHealth=35; game.player.companionStates.sir_kay.health=45; game.player.currentGold=12; renderDestination()")
        devtools.click('[data-action="rest-at-inn"]')
        check("game.player.arthurHealth===40 && game.player.companionStates.sir_kay.health===50 && game.player.currentGold===9", "Party rest exceeded a maximum or charged more than once")
        check("document.querySelector('[data-action=\"rest-at-inn\"]')?.disabled && HealingRules.quoteInnRest(game.player).goldCost===0", "Full-health rest can still charge resources")

        devtools.evaluate("game.player.arthurHealth=12; game.player.companionStates.sir_kay.health=21; game.player.currentGold=12; renderDestination()")
        devtools.click('[data-action="rest-at-inn"]')
        check("game.player.arthurHealth===22&&game.player.companionStates.sir_kay.health===31&&game.player.currentGold===9&&!document.querySelector('[data-action=\"rest-at-inn\"]')?.disabled", "First repeated Inn rest did not preserve another valid rest")
        devtools.click('[data-action="rest-at-inn"]')
        check("game.player.arthurHealth===32&&game.player.companionStates.sir_kay.health===41&&game.player.currentGold===6&&!document.querySelector('[data-action=\"rest-at-inn\"]')?.disabled", "Second repeated Inn rest did not heal and charge independently")
        devtools.click('[data-action="rest-at-inn"]')
        check("game.player.arthurHealth===40&&game.player.companionStates.sir_kay.health===50&&game.player.currentGold===3&&document.querySelector('[data-action=\"rest-at-inn\"]')?.disabled&&SaveSystem.load().arthurHealth===40&&SaveSystem.load().companionStates.sir_kay.health===50", "Repeated Inn rests did not cap, stop, or save correctly")

        devtools.evaluate("game.player.arthurHealth=7; game.player.companionStates.sir_kay.health=50; game.player.currentGold=6; renderDestination()")
        devtools.click('[data-action="rest-at-inn"]')
        devtools.click('[data-action="rest-at-inn"]')
        check("game.player.arthurHealth===27&&game.player.currentGold===0&&document.querySelector('[data-action=\"rest-at-inn\"]')?.disabled&&document.body.textContent.includes('Cannot Afford Rest')", "Inn allowed another repeated rest without enough gold")

        devtools.evaluate("game.player.arthurHealth=20; game.player.companionStates.sir_kay.health=30; game.player.currentGold=2; savePlayer(); renderDestination()")
        check("!HealingRules.quoteInnRest(game.player).available && document.body.textContent.includes('Cannot Afford Rest')", "Unaffordable Inn healing is not clearly blocked")
        check("(() => { const before=JSON.stringify(game.player); const result=HealingRules.restAtInn(game.player); return !result.applied && JSON.stringify(game.player)===before; })()", "Unaffordable healing mutated player resources")
        check("(() => { const player=SaveSystem.createDefaultPlayerState(); player.selectedCompanion=null; player.arthurHealth=20; player.companionStates.sir_kay.health=30; const result=HealingRules.restAtInn(player); return player.arthurHealth===30 && player.companionStates.sir_kay.health===30 && result.partyMembers.length===1; })()", "A non-selected companion was healed")

        check("(() => { game.player.selectedCompanion='sir_kay'; game.player.arthurHealth=35; game.player.companionStates.sir_kay.health=40; game.player.currentGold=10; game.player.provisions=24; const expedition=ExpeditionRules.startExpedition(game.player,{provisions:5}); expedition.health=27; expedition.companionCombatHp.sir_kay=22; ExpeditionRules.settle(game.player,expedition,true); const persisted=game.player.arthurHealth===27&&game.player.companionStates.sir_kay.health===22; CampaignRules.enterLocation(game.player); const next=ExpeditionRules.startExpedition(game.player,{provisions:5}); return persisted && next.health===27 && next.companionCombatHp.sir_kay===22; })()", "Party damage reset on settlement, town entry, or next expedition start")
        check("(() => { game.expedition=null; game.player.arthurHealth=35; game.player.provisions=24; game.preparationMode='expedition'; game.preparationSupplies=5; startExpedition(); game.expedition.health=29; completeReturn(); const settled=game.screen==='summary'&&game.player.arthurHealth===29&&SaveSystem.load().arthurHealth===29; showLocation(); game.preparationMode='expedition'; game.preparationSupplies=5; startExpedition(); const carried=game.expedition.health===29; game.expedition=null; showScreen('campaign'); return settled&&carried; })()", "Normal game return/save/next departure did not preserve damage")
        check("(() => { const a=SaveSystem.createDefaultPlayerState(); const b=SaveSystem.createDefaultPlayerState(); a.arthurHealth=b.arthurHealth=20; a.companionStates.sir_kay.health=b.companionStates.sir_kay.health=30; a.currentGold=b.currentGold=10; const inn=HealingRules.restAtInn(a); const decision=applyBetweenExpeditionPolicy(b,CampaignRules.createShopStocks(),BetweenExpeditionPolicies['conservative-sustainer'],25,true); return JSON.stringify(inn.healingByPartyMember)===JSON.stringify(decision.healing.healingByPartyMember) && a.arthurHealth===b.arthurHealth && a.companionStates.sir_kay.health===b.companionStates.sir_kay.health && inn.goldCost===decision.healing.goldCost && a.currentGold===b.currentGold; })()", "Inn and campaign party healing diverged")
        check("(() => { const manual=SaveSystem.createDefaultPlayerState(); const automated=SaveSystem.createDefaultPlayerState(); manual.arthurHealth=automated.arthurHealth=12; manual.companionStates.sir_kay.health=automated.companionStates.sir_kay.health=21; manual.currentGold=automated.currentGold=12; const first=HealingRules.restAtInn(manual); const second=HealingRules.restAtInn(manual); const decision=applyBetweenExpeditionPolicy(automated,CampaignRules.createShopStocks(),BetweenExpeditionPolicies['conservative-sustainer'],25,true,'cautious'); return first.applied&&second.applied&&decision.healing.restActionCount===2&&manual.arthurHealth===automated.arthurHealth&&manual.companionStates.sir_kay.health===automated.companionStates.sir_kay.health&&manual.currentGold===automated.currentGold&&decision.healing.goldCost===6; })()", "Repeated campaign healing diverged from consecutive production Inn rests")
        check("(() => { const campaign=CampaignSimulationRunner.run({seed:'revive-kay',expeditions:1,turnaroundDistance:1,startingState:{arthurHealth:20,companionStates:{sir_kay:{health:0}},currentGold:100,provisions:30}}); const healing=campaign.betweenExpeditionDecisions[0].healing; return campaign.completedPlan&&healing.healingByPartyMember.arthur===20&&healing.healingByPartyMember.sir_kay===40&&campaign.healingByPartyMember.sir_kay===40&&healing.restActionCount===4&&campaign.totalHealingCost===12; })()", "Campaign did not repeat the shared Inn action until its party threshold was met")
        check("(() => { const policy=BetweenExpeditionPolicies['aggressive-reinvestor']; const healthy=SaveSystem.createDefaultPlayerState(); healthy.arthurHealth=21; healthy.currentGold=100; const healthyDecision=applyBetweenExpeditionPolicy(healthy,CampaignRules.createShopStocks(),policy,25,true); const boundary=SaveSystem.createDefaultPlayerState(); boundary.arthurHealth=20; boundary.currentGold=100; const boundaryDecision=applyBetweenExpeditionPolicy(boundary,CampaignRules.createShopStocks(),policy,25,true); const low=SaveSystem.createDefaultPlayerState(); low.arthurHealth=19; low.currentGold=100; const lowDecision=applyBetweenExpeditionPolicy(low,CampaignRules.createShopStocks(),policy,25,true); const critical=SaveSystem.createDefaultPlayerState(); critical.arthurHealth=9; critical.currentGold=100; const criticalDecision=applyBetweenExpeditionPolicy(critical,CampaignRules.createShopStocks(),policy,25,true); return policy.healingThreshold===0.5 && !healthyDecision.healing.attempted && !boundaryDecision.healing.attempted && lowDecision.healing.applied && low.arthurHealth===29 && lowDecision.healing.restActionCount===1 && lowDecision.healingTriggerReason==='arthur-low-below-50-percent' && criticalDecision.healing.applied && critical.arthurHealth===29 && critical.currentGold===94 && criticalDecision.healing.restActionCount===2 && criticalDecision.healing.healingByPartyMember.arthur===20 && criticalDecision.healingTriggerReason==='arthur-critical-below-25-percent' && lowDecision.healingThresholdComparison==='below'; })()", "Aggressive healing thresholds or critical-priority behavior are invalid")
        check("(() => { const player=SaveSystem.createDefaultPlayerState(); player.arthurHealth=19; player.companionStates.sir_kay.health=30; player.currentGold=2; player.provisions=30; const decision=applyBetweenExpeditionPolicy(player,CampaignRules.createShopStocks(),BetweenExpeditionPolicies['aggressive-reinvestor'],25,true); const kay=decision.healing.partyMembers.find(member=>member.id==='sir_kay'); return decision.healing.attempted && !decision.healing.applied && decision.healing.healthBefore===19 && decision.healing.healthAfter===19 && decision.healing.healingAmount===0 && decision.healing.quotedHealthAfter===29 && decision.healing.quotedHealingAmount===10 && decision.healing.goldCost===0 && decision.healing.quotedGoldCost===3 && kay.healthAfter===30 && kay.healingAmount===0 && kay.quotedHealthAfter===40 && kay.quotedHealingAmount===10; })()", "Unaffordable healing telemetry reports quoted recovery as applied")
        check("(() => { const make=()=>{const player=SaveSystem.createDefaultPlayerState(); player.currentGold=0; player.provisions=20; return player;}; const policy=BetweenExpeditionPolicies['conservative-sustainer']; const cautious=applyBetweenExpeditionPolicy(make(),CampaignRules.createShopStocks(),policy,75,true,'cautious'); const random=applyBetweenExpeditionPolicy(make(),CampaignRules.createShopStocks(),policy,75,true,'random'); const aggressive=applyBetweenExpeditionPolicy(make(),CampaignRules.createShopStocks(),policy,75,true,'aggressive'); return cautious.encounterProvisionReserve===4&&random.encounterProvisionReserve===3&&aggressive.encounterProvisionReserve===2&&cautious.desiredProvisionStockForNominalDistance===Math.ceil(cautious.desiredTargetPassiveFoodEstimate+cautious.preferredSafetyMargin+4)&&cautious.totalEstimatedProvisionRequirement>=cautious.departurePassiveFoodEstimate+4&&aggressive.actualTargetDistance>random.actualTargetDistance&&random.actualTargetDistance>cautious.actualTargetDistance; })()", "Strategy encounter reserves do not affect deterministic departure planning")
        check("(() => { const expedition={direction:'outbound',distance:20,provisions:4,provisionConsumptionMultiplier:1.3,nextEncounterAt:21,seenEncounterIds:['future-a']}; const changedFuture={...expedition,nextEncounterAt:200,seenEncounterIds:['future-b'],activeEncounter:{encounterId:'unknown-future'}}; const first=SimulationProvisionPlanning.emergencyTurnaround(expedition,'random'); const second=SimulationProvisionPlanning.emergencyTurnaround(changedFuture,'random'); return first.shouldTurn&&JSON.stringify(first)===JSON.stringify(second)&&first.encounterReserve===3&&first.totalReturnRequirement===second.totalReturnRequirement; })()", "Emergency provision planning used future encounter knowledge")
        check("(() => { const run=SimulationRunner.run({seed:'emergency-food-return',strategy:'cautious',provisions:5,turnaroundPolicy:{type:'fixedDistance',distance:100}}); const decision=run.decisions.find(entry=>entry.type==='emergency-provision-turnaround'); return run.returnedSafely&&run.emergencyProvisionTurnaround&&run.emergencyProvisionTurnaroundDistance>0&&run.emergencyProvisionTurnaroundDistance<100&&run.turnaroundDistance===run.emergencyProvisionTurnaroundDistance&&run.originalTargetDistance===100&&run.encounterProvisionReserve===4&&decision?.originalTargetDistance===100&&run.replay.decisions.some(entry=>entry.type==='emergency-provision-turnaround'); })()", "Outbound simulation did not record a safe emergency provision turnaround")
        check("(() => { const player=SaveSystem.createDefaultPlayerState(); player.arthurHealth=20; player.currentGold=0; player.provisions=15; const decision=applyBetweenExpeditionPolicy(player,CampaignRules.createShopStocks(),BetweenExpeditionPolicies['conservative-sustainer'],75,true); const types=decision.strategyConstraints.map(entry=>entry.type); return decision.healing.attempted&&!decision.healing.applied&&!decision.hardFailure&&decision.stopReason===null&&decision.actualTargetDistance>=1&&decision.actualTargetDistance<75&&types.includes('preferred-healing-unaffordable')&&types.includes('target-distance-reduced'); })()", "Unaffordable preferred healing terminated a viable reduced-distance departure")
        check("(() => { const campaign=CampaignSimulationRunner.run({seed:'continue-solo',expeditions:1,strategy:'cautious',betweenExpeditionPolicy:'conservative-sustainer',turnaroundDistance:75,startingState:{arthurHealth:40,companionStates:{sir_kay:{health:0}},currentGold:0,provisions:15}}); const decision=campaign.betweenExpeditionDecisions[0]; const types=decision.strategyConstraints.map(entry=>entry.type); return campaign.expeditionsAttempted===1&&campaign.completedPlan&&!campaign.hardFailure&&campaign.endingState.selectedCompanion===null&&types.includes('preferred-healing-unaffordable')&&types.includes('active-companion-unavailable')&&campaign.strategyConstraintCount>=2; })()", "An unaffordable companion rest stopped a campaign that could continue solo")
        check("(() => { const player=SaveSystem.createDefaultPlayerState(); player.provisions=1; player.currentGold=0; const stocks=CampaignRules.createShopStocks(); stocks.village_general_goods=0; const decision=applyBetweenExpeditionPolicy(player,stocks,BetweenExpeditionPolicies['conservative-sustainer'],75,true); return decision.preferredSafeDistance===0&&decision.encounterReserveSupportedDistance===0&&decision.minimumSupportedDistance>=1&&decision.actualTargetDistance>=1&&decision.stopReason===null&&decision.safetyMargin===0&&decision.encounterProvisionReserveUsed===0&&decision.targetDistanceReductionReason==='expected-encounter-reserve-unavailable'; })()", "Preferred safety reserves were incorrectly treated as the real expedition minimum")
        check("(() => { const player=SaveSystem.createDefaultPlayerState(); player.provisions=100; player.currentGold=0; const decision=applyBetweenExpeditionPolicy(player,CampaignRules.createShopStocks(),BetweenExpeditionPolicies['conservative-sustainer'],500,true); return decision.provisionStockAvailableToPack===ExpeditionRules.partyProvisionCapacity(player.selectedCompanion) && decision.estimatedProvisionRequirementForChosenDistance<=decision.provisionStockAvailableToPack && decision.actualTargetDistance<500; })()", "Persistent stock above pack capacity inflated the supported distance")
        check("(() => { const make=()=>{const player=SaveSystem.createDefaultPlayerState(); player.provisions=15; player.currentGold=0; return player;}; const conservative=applyBetweenExpeditionPolicy(make(),CampaignRules.createShopStocks(),BetweenExpeditionPolicies['conservative-sustainer'],75,true); const aggressive=applyBetweenExpeditionPolicy(make(),CampaignRules.createShopStocks(),BetweenExpeditionPolicies['aggressive-reinvestor'],75,true); return conservative.actualTargetDistance<75 && conservative.actualTargetDistance>=1 && aggressive.actualTargetDistance<=75 && conservative.actualTargetDistance<=aggressive.actualTargetDistance && conservative.targetDistanceReduced && conservative.targetDistanceReductionReason && conservative.desiredProvisionStockForNominalDistance>conservative.actualProvisionStockAfterPurchase && conservative.estimatedProvisionRequirementForChosenDistance<=conservative.actualProvisionStockAfterPurchase; })()", "Adaptive distance or policy-specific safety margins are invalid")
        check("(() => { const campaign=CampaignSimulationRunner.run({seed:'adapt-not-stop',expeditions:1,strategy:'cautious',betweenExpeditionPolicy:'conservative-sustainer',turnaroundDistance:75,startingState:{currentGold:0,provisions:15}}); const decision=campaign.betweenExpeditionDecisions[0]; return campaign.expeditionsAttempted===1 && campaign.stopReason!=='cannot-support-any-expedition' && decision.actualTargetDistance<decision.desiredTargetDistance && campaign.expeditions[0].actualTargetDistance===decision.actualTargetDistance; })()", "Campaign terminated instead of launching a shorter affordable expedition")
        check("(() => { const campaign=CampaignSimulationRunner.run({seed:'town-floor-continues',expeditions:1,strategy:'cautious',betweenExpeditionPolicy:'conservative-sustainer',turnaroundDistance:100,startingState:{currentGold:0,provisions:0}}); return campaign.betweenExpeditionDecisions[0].townProvisionGrant===10 && campaign.expeditionsAttempted===1 && campaign.stopReason!=='cannot-support-any-expedition'; })()", "Production town safety net was incorrectly treated as insolvency")
        check("(() => { const player=SaveSystem.createDefaultPlayerState(); player.provisions=0; player.currentGold=0; const stocks=CampaignRules.createShopStocks(); stocks.village_general_goods=0; const decision=applyBetweenExpeditionPolicy(player,stocks,BetweenExpeditionPolicies['conservative-sustainer'],75,true); return decision.actualTargetDistance===0 && decision.stopReason==='cannot-support-any-expedition' && decision.hardFailure && decision.hardFailureReason==='cannot-support-any-expedition' && !decision.preferredProvisionTargetMet; })()", "True inability to support any expedition lacks an accurate hard-failure reason")
        check("(() => { const player=SaveSystem.createDefaultPlayerState(); const expedition=ExpeditionRules.startExpedition(player,{provisions:10,health:5}); const combat=CombatSystem.create(expedition,'wolves',{random:()=>0}); combat.status='awaitingAction'; combat.activeActorId='arthur'; combat.allies.find(ally=>ally.id==='arthur').gauge=100; combat.enemies.forEach(enemy=>enemy.gauge=99); let emergency=null; const action=SimulationStrategies.aggressive.chooseCombatAction(combat,expedition,{random:()=>0,recordEmergency:value=>{emergency=value;}}); return action==='defend' && emergency?.reason==='lethal-damage-before-next-action' && emergency.arthurHealth===5 && emergency.estimatedIncomingDamage>=5 && emergency.estimatedDefendedDamage<5; })()", "Aggressive emergency Defend behavior did not trigger at critical health")
        check("(() => { const player=SaveSystem.createDefaultPlayerState(); const expedition=ExpeditionRules.startExpedition(player,{provisions:10,health:40}); const combat=CombatSystem.create(expedition,'wolves',{random:()=>0}); combat.status='awaitingAction'; combat.activeActorId='arthur'; combat.allies.find(ally=>ally.id==='arthur').gauge=100; combat.enemies.forEach(enemy=>enemy.gauge=99); let emergency=null; const action=SimulationStrategies.aggressive.chooseCombatAction(combat,expedition,{random:()=>0,recordEmergency:value=>{emergency=value;}}); return action==='attack' && emergency===null; })()", "Aggressive stopped attacking without a lethal emergency")
        check("(() => { const batch=SimulationRunner.runBatch({scenarios:[{id:'emergency-telemetry',strategy:'aggressive',turnaroundPolicy:{type:'fixedDistance',distance:100},startingState:{health:8}}],runsPerScenario:40,seed:'emergency-telemetry'}); return batch.summary.averageAggressiveEmergencyActions>0 && batch.summary.averageCombatsStartedBelow25Percent>0 && batch.results.some(run=>run.aggressiveEmergencyActions>0 && run.combats.some(combat=>combat.aggressiveEmergencyActions.length>0)) && batch.results.some(run=>run.combatsStartedBelow50Percent>0 && run.combatsStartedBelow25Percent>0 && run.events.some(event=>event.type==='combat-start'&&event.arthurEnteredBelow25Percent)); })()", "Aggressive emergency or low-health combat-entry telemetry was not recorded")
        check("(() => { const player=SaveSystem.createDefaultPlayerState(); const expedition=ExpeditionRules.startExpedition(player,{provisions:10}); const arthurCombat=CombatSystem.create(expedition,'wild_boar',{random:()=>0.1}); const kayCombat=CombatSystem.create(expedition,'wild_boar',{random:()=>0.9}); return chooseEnemyTarget(arthurCombat,COMBAT_ENEMY_ACTION_DEFINITIONS.boar_charge).id==='arthur' && chooseEnemyTarget(kayCombat,COMBAT_ENEMY_ACTION_DEFINITIONS.boar_charge).id==='sir_kay'; })()", "Weighted production targeting cannot select both Arthur and Kay")
        check("(() => { const player=SaveSystem.createDefaultPlayerState(); const expedition=ExpeditionRules.startExpedition(player,{provisions:10}); const combat=CombatSystem.create(expedition,'wild_boar',{random:()=>0.9}); combat.allies.find(ally=>ally.id==='sir_kay').hp=0; const livingTarget=chooseEnemyTarget(combat,COMBAT_ENEMY_ACTION_DEFINITIONS.boar_charge)?.id; expedition.selectedCompanion=null; const solo=CombatSystem.create(expedition,'wild_boar',{random:()=>0.9}); return livingTarget==='arthur' && chooseEnemyTarget(solo,COMBAT_ENEMY_ACTION_DEFINITIONS.boar_charge)?.id==='arthur'; })()", "Dead companion or solo targeting is invalid")
        check("(() => { const sequence=seed=>{ const player=SaveSystem.createDefaultPlayerState(); const expedition=ExpeditionRules.startExpedition(player,{provisions:10}); const random=GameRandom.create(seed); const combat=CombatSystem.create(expedition,'wild_boar',{random:random.random}); return Array.from({length:30},()=>chooseEnemyTarget(combat,COMBAT_ENEMY_ACTION_DEFINITIONS.boar_charge).id); }; const first=sequence('target-sequence'); const second=sequence('target-sequence'); return JSON.stringify(first)===JSON.stringify(second) && first.includes('arthur') && first.includes('sir_kay'); })()", "Seeded target selection is not deterministic or does not reach both allies")
        check("(() => { const player=SaveSystem.createDefaultPlayerState(); player.currentGold=12; const expedition=ExpeditionRules.startExpedition(player,{provisions:10}); const combat=CombatSystem.create(expedition,'wild_boar',{random:()=>0.99}); combat.enemies[0].gauge=100; CombatSystem.update(combat,expedition,0); const event=combat.events.find(entry=>entry.actor==='wild_boar_1'); ExpeditionRules.settle(player,expedition,true); SaveSystem.save(player); const wounded=SaveSystem.load(); const carried=ExpeditionRules.startExpedition(wounded,{provisions:1}).companionCombatHp.sir_kay===39; const healing=HealingRules.restAtInn(wounded); SaveSystem.save(wounded); const healed=SaveSystem.load(); const next=ExpeditionRules.startExpedition(healed,{provisions:1}); return event?.selectedTarget==='sir_kay' && event?.target==='sir_kay' && player.companionStates.sir_kay.health===39 && carried && healing.healingByPartyMember.sir_kay===10 && healed.companionStates.sir_kay.health===49 && next.companionCombatHp.sir_kay===49; })()", "Kay target damage did not persist, heal, save, or carry into the next expedition")
        check("(() => { const batch=SimulationRunner.runBatch({scenarios:[{id:'party-targeting',strategy:'aggressive',turnaroundPolicy:{type:'fixedDistance',distance:100}}],runsPerScenario:40,seed:'party-targeting'}); const arthurDamage=batch.results.reduce((sum,result)=>sum+(result.damageReceivedByPartyMember.arthur??0),0); const kayDamage=batch.results.reduce((sum,result)=>sum+(result.damageReceivedByPartyMember.sir_kay??0),0); return arthurDamage>0 && kayDamage>0 && batch.results.some(result=>result.combats.some(combat=>Number.isFinite(combat.attacksReceivedByPartyMember.arthur)&&Number.isFinite(combat.damageReceivedByPartyMember.sir_kay)&&combat.actionEvents.some(event=>event.selectedTarget))); })()", "Per-member target, attack, or damage telemetry is incomplete")
        check("!campaignCompletedPlan({maxExpeditions:10},Array.from({length:10},()=>({success:false})), 'arthur-died') && campaignCompletedPlan({maxExpeditions:10},Array.from({length:10},()=>({success:true})), 'max-expeditions-reached')", "Final-expedition death still counts as campaign completion")
        check("(() => { const death=Array.from({length:100},(_,index)=>CampaignSimulationRunner.run({seed:`final-death-${index}`,expeditions:1,strategy:'aggressive',betweenExpeditionPolicy:'aggressive-reinvestor',turnaroundDistance:100,healingEnabled:false,startingState:{arthurHealth:1,currentGold:0,provisions:30}})).find(campaign=>campaign.stopReason==='arthur-died'&&campaign.expeditionsAttempted===1); return death && !death.completedPlan && death.hardFailure && death.stopCategory==='hard-failure' && death.expeditions[0].hardFailureReason==='arthur-died'; })()", "An actual death lacks correct hard-failure or completion semantics")
        check("campaignStopCategory('expedition-resource-exhaustion')==='hard-failure'&&isCampaignResourceExhaustion('The company exhausted its provisions during the encounter.')", "Expedition resource exhaustion is not recognized as a hard campaign failure")

        check("CampaignSimulationRunner.verifyDeterminism({seed:'campaign-repeat',expeditions:10,strategy:'random',betweenExpeditionPolicy:'conservative-sustainer',turnaroundDistance:25,startingState:{currentGold:100,provisions:30}}).matches", "Same-seed campaign is not deterministic")
        check("(() => { const signatures=Array.from({length:10},(_,i)=>CampaignSimulationRunner.run({seed:`campaign-diverge-${i}`,expeditions:5,strategy:'random',betweenExpeditionPolicy:'minimal-restock',turnaroundDistance:75,startingState:{currentGold:100,provisions:30}})).map(result=>JSON.stringify(result.expeditions.map(entry=>({outcome:entry.outcome,health:entry.endingHealth,encounters:entry.expeditionTelemetry.encounters.map(e=>e.encounterId)})))); return new Set(signatures).size>1; })()", "Different campaign seeds did not diverge")
        check("(() => { const campaign=CampaignSimulationRunner.run({seed:'ten-complete',expeditions:10,strategy:'cautious',betweenExpeditionPolicy:'conservative-sustainer',turnaroundDistance:25,startingState:{currentGold:100,provisions:30}}); return campaign.completedPlan && campaign.expeditionsAttempted===10 && campaign.expeditionsReturned===10 && campaign.replay.expeditionSeeds.length===10; })()", "Viable 10-expedition campaign did not complete")
        check("(() => { const campaign=CampaignSimulationRunner.run({seed:'persistence',expeditions:4,strategy:'aggressive',betweenExpeditionPolicy:'minimal-restock',turnaroundDistance:75,startingState:{currentGold:100,provisions:30}}); return campaign.expeditions.every((entry,index)=>index===0 || entry.stateBefore.gold===campaign.expeditions[index-1].stateAfter.gold) && campaign.expeditions.every(entry=>entry.stateAfter.provisionStock>=0); })()", "Gold/provision campaign state did not carry between expeditions")
        check("(() => { const batch=CampaignSimulationRunner.runBatch({scenarios:[{id:'batch',strategy:'cautious',betweenExpeditionPolicy:'conservative-sustainer',turnaroundDistance:25,startingState:{currentGold:100,provisions:30}}],campaignsPerScenario:12,expeditionsPerCampaign:10}); const csv=CampaignSimulationTelemetry.expeditionsToCsv(batch); const campaignsCsv=CampaignSimulationTelemetry.campaignsToCsv(batch); return batch.results.length===12 && batch.summary.totalCampaigns===12 && batch.summary.campaignCompletionRate===1 && Number.isFinite(batch.summary.averageDesiredExpeditionDistance) && Number.isFinite(batch.summary.averageActualExpeditionDistance) && Number.isFinite(batch.summary.targetDistanceReductionFrequency) && Number.isFinite(batch.summary.averageDistanceReduced) && Number.isFinite(batch.summary.hardFailureRate) && Number.isFinite(batch.summary.averageStrategyConstraintCount) && Number.isFinite(batch.summary.emergencyProvisionTurnaroundRate) && campaignsCsv.split('\\n').length===13 && campaignsCsv.includes('stopCategory') && campaignsCsv.includes('strategyConstraintTypes') && campaignsCsv.includes('totalEmergencyProvisionTurnarounds') && csv.includes('desiredTargetDistance') && csv.includes('actualTargetDistance') && csv.includes('departurePassiveFoodEstimate') && csv.includes('encounterProvisionReserve') && csv.includes('totalEstimatedProvisionRequirement') && csv.includes('emergencyProvisionTurnaroundDistance') && csv.includes('provisionExhaustionFailure') && csv.includes('strategyConstraintTypes') && csv.includes('hardFailureReason') && csv.includes('arthurHealing') && csv.includes('companionHealing') && csv.includes('healingCost'); })()", "Campaign batch, provision planning, stop classification, or CSV export is invalid")
        check("(() => { const campaign=CampaignSimulationRunner.run({seed:'replay',expeditions:3,turnaroundDistance:25,startingState:{currentGold:100,provisions:30}}); return campaign.replay.campaignSeed==='replay' && campaign.replay.expeditionSeeds.every((seed,index)=>seed===`replay:expedition-${index}`) && campaign.replay.expeditionReplays.length===campaign.expeditionsAttempted && campaign.betweenExpeditionDecisions.length>=campaign.expeditionsAttempted; })()", "Campaign replay payload is incomplete")

        if devtools.console_errors:
            raise AssertionError(f"Runtime exceptions: {devtools.console_errors}")
        print(f"PASS: {checks} campaign/health/Inn assertions")
    finally:
        server.shutdown()
        chrome.terminate()
        try:
            chrome.wait(timeout=3)
        except subprocess.TimeoutExpired:
            chrome.kill()
        shutil.rmtree(profile, ignore_errors=True)


if __name__ == "__main__":
    run()
